- name: Install Nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: Removing old web content
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: Download Nginx WebContent and Extract it
  ansible.builtin.unarchive:
    src: https://github.com/roboshop-devops-project/frontend/archive/main.zip
    dest: /tmp
    remote_src: yes

- name: Copy extracted file
  ansible.builtin.copy:
    src: /tmp/frontend-main/static/
    dest: /usr/share/nginx/html/
    remote_src: yes

- name: Copy roboshop Nginx config file
  ansible.builtin.copy:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: Start nginx service
  ansible.builtin.systemd:
    enabled: yes
    state: restarted
    name: nginx




#  echo "update Roboshop Config file"
#  for component in catalogue user cart shipping payment ; do
#  sed -i -e "/$component/ s/localhost/$component.roboshop.internal" /etc/nginx/default.d/roboshop.conf &>>$LOG_FILE
#  done
  
#  sed -i -e '/catalogue/ s/localhost/catalogue.roboshop.internal/' -e '/user/ s/localhost/user.roboshop.internal/' -e '/cart/ s/localhost/cart.roboshop.internal/' -e '/shipping/ s/localhost/shipping.roboshop.internal/' -e '/payment/ s/localhost/payment.roboshop.internal/' /etc/nginx/default.d/roboshop.conf &>>$LOG_FILE
#  StatusCheck $?
